Rails:
  Enabled: true
Rails/ApplicationRecord:
  Exclude:
    - 'lib/**/*'
Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template

# 'old' style
Style/EmptyMethod:
  EnforcedStyle: expanded

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/factories/*'

# None-guard clauses are often clearer for intent
Style/GuardClause:
  Enabled: false

# It makes much more sense to group them according to purpose
Bundler/OrderedGems:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.0

# TODO: Remove once rubocop fixes some bugs
Rails/HasManyOrHasOneDependent:
  Enabled: false
