Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
Metrics/AbcSize:
  Max: 20
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Style/Documentation:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
Style/ModuleFunction:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
