Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
Metrics/AbcSize:
  Max: 20
Style/Documentation:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
