require: rubocop-rails

Rails:
  Enabled: true
Rails/ApplicationRecord:
  Exclude:
    - 'lib/**/*'
Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 30
Metrics/ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 250
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
Layout/EmptyLineAfterGuardClause:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2
  AllowedNames:
    - _

# 'old' style
Style/EmptyMethod:
  EnforcedStyle: expanded

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/factories/*'

# None-guard clauses are sometimes clearer
Style/GuardClause:
  Enabled: false

# It makes much more sense to group them according to purpose than alphabetically
Bundler/OrderedGems:
  Enabled: false

# This doesn't always make sense
Rails/InverseOf:
  Enabled: false

Rails/HttpPositionalArguments:
  # Broken for
  Exclude:
    - 'spec/requests/api/v1/**/*'

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

# TODO: Remove once rubocop fixes some bugs
Rails/HasManyOrHasOneDependent:
  Enabled: false

# TODO: Remove once rubocop fixes some bugs
Layout/HashAlignment:
  Enabled: false

# TODO: Fix
Rails/LinkToBlank:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false

# New
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
