shared:
  # Toggle Discord integration (allow users to link Discord account, and show accounts on profile)
  discord_integration: true
  name_filtering:
    enabled: false
    filter: '\A[\p{Alnum}]+\z'
