name: Rails
on:
  - push
  - workflow_dispatch

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_WITHOUT: development

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: citadel
          POSTGRES_PASSWORD: citadel
        ports: ["5432:5432"]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get -yqq install libpq-dev libyaml-dev build-essential libcurl4-openssl-dev
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.6
        bundler-cache: true
    - name: Setup database
      env:
        RAILS_ENV: test
        PGHOST: localhost
      run: |
        cp config/database.yml.github config/database.yml
        bundle exec rake "parallel:setup"
    - name: Run tests
      env:
        RAILS_ENV: test
        PGHOST: localhost
      run: bundle exec rake test
